name       : xorg-cf-files
version    : 1.0.6
release    : 1
source     :
    - https://www.x.org/releases/individual/util/xorg-cf-files-1.0.6.tar.gz : 6d56094e5d1a6c7d7a9576ac3a0fc2c042344509ea900d59f4b23df668b96c7a
license    : MIT
component  : xorg.proto
summary    : Data files for imake
description: |
    The xorg-cf-files package contains the data files for the imake utility,
    defining the known settings for a wide variety of platforms (many of which
    have not been verified or tested in over a decade), and for many of the
    libraries formerly delivered in the X.Org monolithic releases.
builddeps  :
    - pkgconfig(xorg-macros)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
