name       : xorg-cf-files
version    : 1.0.7
release    : 2
source     :
    - https://www.x.org/releases/individual/util/xorg-cf-files-1.0.7.tar.gz : a49478ba0c2138bc53de38979cd2dee073b6fd6728597c552d266a707747f472
license    : MIT
component  : xorg.proto
summary    : Data files for imake
description: |
    The xorg-cf-files package contains the data files for the imake utility,
    defining the known settings for a wide variety of platforms (many of which
    have not been verified or tested in over a decade), and for many of the
    libraries formerly delivered in the X.Org monolithic releases.
builddeps  :
    - pkgconfig(xorg-macros)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
